### ISSUE TITLE
Any chance to slightly update this extension to be 4.6 ready

### ISSUE THREAD

**Issue by magnolia61** [JohnFF/UK-Phone-Number-Validator#3]
Hi John, This extension is very usefull. It should probably deserve a place in core in a section called data cleaning & reconciliation. Would there be any change to slightly update this extension to be ready for use in 4.5 & 4.6?
I will further test myself on 4.6. Current list of 'bugs':
- extension does not create menu item
- the rest seems to work ok. I will update this post.

**Comment by JohnFF** [comment]
Dear Richard,

As it happens, I am redeveloping it to have many, many improvements. It
will be 4.5 & 4.6 compatible and support multiple countries.

(If you or your org want to throw me a buck to help speed up development I
would be much obliged - otherwise I can't do it ahead of work that I am
being contracted for!)

Yours,

John
